# Contoh Basic postgresql.conf Tuning untuk MVP Production (Target: 4 GB RAM, 2 CPU)
listen_addresses = '*'
max_connections = 200
shared_buffers = 1GB                  # 25% dari total RAM (Saran standar PostgreSQL)
effective_cache_size = 3GB            # 75% dari RAM dikurangi Shared Buffers
maintenance_work_mem = 256MB          # Mempercepat Vaccum/Create Index
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1                # Berasumsi Storage AWS EBS / Azure Disk Premium memakai SSD (bukan 4.0 HDD)
effective_io_concurrency = 200        # Optimasi asynchronous I/O read dari SSD NVMe
work_mem = 5MB                        # Memperkuat query multi-tenant dengan sort/join array besar
min_wal_size = 1GB
max_wal_size = 4GB
